"""Provider-neutral, immutable contracts shared by AL/X boundaries."""

from alx.contracts.cognition import Cognition, CognitionOrigin
from alx.contracts.task import ExternalTask, TaskObservation, TaskState
from alx.contracts.review import (
    REVIEW_FAILURES,
    ReviewError,
    ReviewOutcome,
    ReviewRequest,
)
from alx.contracts.repository import (
    MERGE_FAILURES,
    MergeError,
    MergeOutcome,
    MergeRequest,
)
from alx.contracts.coding import (
    CODING_FAILURES,
    CodingError,
    CodingOutcome,
    CodingRequest,
    CodingSession,
    CodingSessionResult,
)
from alx.contracts.continuity import (
    AutonomousResponseTransport,
    run_core_worker,
    AutonomousSpendAuthority,
    ResponseDelivery,
    CognitionOpportunity,
    CognitionOpportunitySource,
    DuplicateFutureCognition,
    FutureCognitionNotFound,
    FutureCognitionRequest,
    FutureCognitionStatus,
    FutureCognitionTooSoon,
)
from alx.contracts.sandbox import (
    ArtifactMetadata,
    DAILY_RUNS,
    DAILY_WALL_SECONDS,
    DEFAULT_WALL_SECONDS,
    FileChange,
    MAX_REPORTED_ARTIFACTS,
    MAX_STDERR_CHARACTERS,
    MAX_STDOUT_CHARACTERS,
    MAX_WALL_SECONDS,
    SANDBOX_FAILURES,
    SandboxError,
    SandboxOutcome,
    SandboxRequest,
)
from alx.contracts.web import (
    CONNECT_TIMEOUT_SECONDS,
    TOTAL_DEADLINE_SECONDS,
    MAX_DURABLE_METADATA_CHARACTERS,
    MAX_URL_CHARACTERS,
    MAX_PUBLISHER_CHARACTERS,
    MAX_TITLE_CHARACTERS,
    DEFAULT_SEARCH_RESULTS,
    MAX_SEARCH_RESULTS,
    MAX_SNIPPET_CHARACTERS,
    MAX_SUBJECT_CHARACTERS,
    MAX_AGE_CHARACTERS,
    MAX_SEARCH_PAYLOAD_CHARACTERS,
    WEB_SEARCH_FAILURES,
    WebSearchError,
    WebSearchProvider,
    WebSearchResult,
    WebSearchResults,
    ALLOWED_CONTENT_TYPES,
    ALLOWED_PORTS,
    ALLOWED_SCHEMES,
    MAX_DOWNLOAD_BYTES,
    MAX_EXTRACTED_CHARACTERS,
    MAX_REDIRECTS,
    WEB_FETCH_FAILURES,
    PublicAddress,
    PublicUrl,
    WebFetchProvider,
    WebPage,
    WebRetrievalError,
)
from alx.contracts.usage import (
    CANONICAL_FIELDS,
    is_measured,
    normalise_usage,
)
from alx.contracts.notebook import (
    DeletionRecord,
    EntryKind,
    EntryProposal,
    EntryRevision,
    EntryRevisionProposal,
    EntrySnapshot,
    ResearchQuery,
    RevisionAuthor,
    ThreadProposal,
    ThreadSnapshot,
    ThreadStatus,
)
from alx.contracts.research import (
    ResearchLedger,
    ResearchModelUnpriced,
    ResearchPricing,
    ResearchQuestion,
    Reservation,
)
from alx.contracts.records import (
    Approval,
    ApprovalProposal,
    ApprovalLifecycle,
    ApprovalScope,
    BackgroundEvent,
    CapabilityCall,
    CapabilityAttempt,
    CapabilityAttemptDisposition,
    CapabilityResult,
    CapabilityResultState,
    ConversationOrigin,
    ConversationTurn,
    Evidence,
    history_evidence_ids,
    GoalMutationKind,
    GoalProposal,
    GoalState,
    GoalStatus,
    GoalStopReason,
    Objective,
    ProgressRecord,
    Referent,
    SuccessCriterion,
    WorkItem,
)
from alx.contracts.provenance import (
    ContentOrigin,
    ContentProvenance,
    ContentTombstone,
    ExpiryReason,
    RetentionPolicy,
)
from alx.contracts.capabilities import CapabilityDefinition, SideEffect, StructuredSchema, ValueKind
from alx.contracts.core import AgentDecision, CapabilityDispatch, ConversationSnapshot, DecisionValidationError, DurableConversationStore, DurableGoalStore, DurableMemoryStore, GoalSnapshot, GoalSummary, PendingMemoryBatch, ReasoningContext, ReasoningProvider
from alx.contracts.records import StructuredData
from alx.contracts.specialists import SpecialistError, SpecialistModel, SpecialistQuestion
from alx.contracts.speech import (
    AudioChunk,
    SpeechSynthesizer,
    SpeechTranscriber,
    TranscriptionEvent,
    TranscriptionState,
)
from alx.contracts.models import (
    ModelCompletion,
    ModelMessage,
    ModelRequest,
    ModelRole,
    ReasoningModel,
)
from alx.contracts.memory import (
    MemoryCorrection,
    MemoryIdentityConflict, MemoryKind,
    MemoryProposal,
    MemoryQuery,
    MemoryRevision,
    MemorySnapshot,
    MemorySourceMatch,
)
from alx.contracts.mail import (
    MailAccessError,
    MailAccount,
    MailAttachment,
    MailContent,
    MailObservationControl,
    MailParticipants,
    MailReference,
    MailSearchCriteria,
    MailSearchResult,
    MailSendError,
    MailThreading,
    OutboundReply,
    ReplyOutcome,
)
from alx.contracts.xero import xero_date, XeroAccessError, XeroAccountingAccount
from alx.contracts.dhl import DhlDocumentError, DhlImportAnalyzer

__all__ = [
    "ArtifactMetadata",
    "FileChange",
    "SANDBOX_FAILURES",
    "SandboxError",
    "SandboxOutcome",
    "SandboxRequest",
    "DAILY_RUNS",
    "DAILY_WALL_SECONDS",
    "DEFAULT_WALL_SECONDS",
    "MAX_WALL_SECONDS",
    "MAX_REPORTED_ARTIFACTS",
    "MAX_STDOUT_CHARACTERS",
    "MAX_STDERR_CHARACTERS",
    "ExternalTask",
    "TaskObservation",
    "TaskState",
    "REVIEW_FAILURES",
    "ReviewError",
    "ReviewOutcome",
    "ReviewRequest",
    "MERGE_FAILURES",
    "MergeError",
    "MergeOutcome",
    "MergeRequest",
    "CODING_FAILURES",
    "CodingError",
    "CodingOutcome",
    "CodingRequest",
    "CodingSession",
    "CodingSessionResult",
    "CONNECT_TIMEOUT_SECONDS",
    "TOTAL_DEADLINE_SECONDS",
    "MAX_DURABLE_METADATA_CHARACTERS",
    "MAX_URL_CHARACTERS",
    "MAX_PUBLISHER_CHARACTERS",
    "MAX_TITLE_CHARACTERS",
    "DEFAULT_SEARCH_RESULTS",
    "MAX_SEARCH_RESULTS",
    "MAX_SNIPPET_CHARACTERS",
    "MAX_SUBJECT_CHARACTERS",
    "MAX_AGE_CHARACTERS",
    "MAX_SEARCH_PAYLOAD_CHARACTERS",
    "WEB_SEARCH_FAILURES",
    "WebSearchError",
    "WebSearchProvider",
    "WebSearchResult",
    "WebSearchResults",
    "ALLOWED_CONTENT_TYPES",
    "ALLOWED_PORTS",
    "ALLOWED_SCHEMES",
    "MAX_DOWNLOAD_BYTES",
    "MAX_EXTRACTED_CHARACTERS",
    "MAX_REDIRECTS",
    "WEB_FETCH_FAILURES",
    "PublicAddress",
    "PublicUrl",
    "WebFetchProvider",
    "WebPage",
    "WebRetrievalError",
    "CANONICAL_FIELDS",
    "AutonomousResponseTransport", "run_core_worker", "AutonomousSpendAuthority", "ResponseDelivery",
    "Cognition", "CognitionOrigin", "CognitionOpportunity",
    "CognitionOpportunitySource", "FutureCognitionRequest", "FutureCognitionStatus",
    "FutureCognitionNotFound", "DuplicateFutureCognition", "FutureCognitionTooSoon",
    "is_measured",
    "normalise_usage",
    "DeletionRecord",
    "EntryKind",
    "EntryProposal",
    "EntryRevision",
    "EntryRevisionProposal",
    "EntrySnapshot",
    "ResearchQuery",
    "RevisionAuthor",
    "ThreadProposal",
    "ThreadSnapshot",
    "ThreadStatus",
    "ResearchLedger",
    "ResearchModelUnpriced",
    "ResearchPricing",
    "ResearchQuestion",
    "Reservation",
    "RetentionPolicy",
    "ExpiryReason",
    "ContentTombstone",
    "ContentProvenance",
    "ContentOrigin",
    "Approval", "ApprovalProposal", "ApprovalLifecycle", "ApprovalScope", "BackgroundEvent", "CapabilityCall", "CapabilityAttempt", "CapabilityAttemptDisposition",
    "CapabilityResult", "CapabilityResultState", "ConversationOrigin",
    "ConversationTurn", "Evidence", "history_evidence_ids", "GoalMutationKind", "GoalProposal", "GoalState", "GoalStatus", "GoalStopReason",
    "Objective", "ProgressRecord", "Referent", "SuccessCriterion", "WorkItem",
    "CapabilityDefinition", "SideEffect", "StructuredSchema", "ValueKind",
    "StructuredData",
    "SpecialistError", "SpecialistModel", "SpecialistQuestion",
    "AgentDecision", "CapabilityDispatch", "ConversationSnapshot", "DecisionValidationError", "DurableConversationStore", "DurableGoalStore", "DurableMemoryStore", "GoalSnapshot", "GoalSummary", "PendingMemoryBatch", "ReasoningContext", "ReasoningProvider",
    "AudioChunk", "SpeechSynthesizer", "SpeechTranscriber", "TranscriptionEvent",
    "TranscriptionState",
    "ModelCompletion", "ModelMessage", "ModelRequest", "ModelRole",
    "ReasoningModel",
    "MemoryCorrection", "MemoryIdentityConflict", "MemoryKind",
    "MemoryProposal", "MemoryQuery",
    "MemoryRevision", "MemorySnapshot", "MemorySourceMatch",
    "MailAccessError", "MailAccount", "MailAttachment", "MailContent",
    "MailObservationControl", "MailParticipants", "MailReference",
    "MailSearchCriteria", "MailSearchResult",
    "MailSendError", "MailThreading", "OutboundReply", "ReplyOutcome",
    "xero_date",
    "XeroAccessError", "XeroAccountingAccount",
    "DhlDocumentError", "DhlImportAnalyzer",
]
