"""Provider-neutral, immutable contracts shared by AL/X boundaries."""

from alx.contracts.cognition import Cognition, CognitionOrigin
from alx.contracts.continuity import (
    AutonomousResponseTransport,
    AutonomousSpendAuthority,
    ResponseDelivery,
    CognitionOpportunity,
    CognitionOpportunitySource,
    DuplicateFutureCognition,
    FutureCognitionNotFound,
    FutureCognitionRequest,
    FutureCognitionStatus,
    FutureCognitionTooSoon,
)
from alx.contracts.usage import (
    CANONICAL_FIELDS,
    is_measured,
    normalise_usage,
)
from alx.contracts.notebook import (
    DeletionRecord,
    EntryKind,
    EntryProposal,
    EntryRevision,
    EntryRevisionProposal,
    EntrySnapshot,
    ResearchQuery,
    RevisionAuthor,
    ThreadProposal,
    ThreadSnapshot,
    ThreadStatus,
)
from alx.contracts.research import (
    ResearchLedger,
    ResearchModelUnpriced,
    ResearchPricing,
    ResearchQuestion,
    Reservation,
)
from alx.contracts.records import (
    Approval,
    ApprovalProposal,
    ApprovalLifecycle,
    ApprovalScope,
    BackgroundEvent,
    CapabilityCall,
    CapabilityAttempt,
    CapabilityAttemptDisposition,
    CapabilityResult,
    CapabilityResultState,
    ConversationOrigin,
    ConversationTurn,
    Evidence,
    GoalMutationKind,
    GoalProposal,
    GoalState,
    GoalStatus,
    GoalStopReason,
    Objective,
    ProgressRecord,
    Referent,
    SuccessCriterion,
    WorkItem,
)
from alx.contracts.provenance import (
    ContentOrigin,
    ContentProvenance,
    ContentTombstone,
    ExpiryReason,
    RetentionPolicy,
)
from alx.contracts.capabilities import CapabilityDefinition, SideEffect, StructuredSchema, ValueKind
from alx.contracts.core import AgentDecision, CapabilityDispatch, ConversationSnapshot, DecisionValidationError, DurableConversationStore, DurableGoalStore, DurableMemoryStore, GoalSnapshot, GoalSummary, PendingMemoryBatch, ReasoningContext, ReasoningProvider
from alx.contracts.records import StructuredData
from alx.contracts.specialists import SpecialistError, SpecialistModel, SpecialistQuestion
from alx.contracts.speech import (
    AudioChunk,
    SpeechSynthesizer,
    SpeechTranscriber,
    TranscriptionEvent,
    TranscriptionState,
)
from alx.contracts.models import (
    ModelCompletion,
    ModelMessage,
    ModelRequest,
    ModelRole,
    ReasoningModel,
)
from alx.contracts.memory import (
    MemoryCorrection,
    MemoryKind,
    MemoryProposal,
    MemoryQuery,
    MemoryRevision,
    MemorySnapshot,
    MemorySourceMatch,
)
from alx.contracts.mail import (
    MailAccessError,
    MailAccount,
    MailAttachment,
    MailContent,
    MailObservationControl,
    MailParticipants,
    MailReference,
    MailSearchCriteria,
    MailSearchResult,
    MailSendError,
    MailThreading,
    OutboundReply,
    ReplyOutcome,
)
from alx.contracts.xero import xero_date, XeroAccessError, XeroAccountingAccount
from alx.contracts.dhl import DhlDocumentError, DhlImportAnalyzer

__all__ = [
    "CANONICAL_FIELDS",
    "AutonomousResponseTransport", "AutonomousSpendAuthority", "ResponseDelivery",
    "Cognition", "CognitionOrigin", "CognitionOpportunity",
    "CognitionOpportunitySource", "FutureCognitionRequest", "FutureCognitionStatus",
    "FutureCognitionNotFound", "DuplicateFutureCognition", "FutureCognitionTooSoon",
    "is_measured",
    "normalise_usage",
    "DeletionRecord",
    "EntryKind",
    "EntryProposal",
    "EntryRevision",
    "EntryRevisionProposal",
    "EntrySnapshot",
    "ResearchQuery",
    "RevisionAuthor",
    "ThreadProposal",
    "ThreadSnapshot",
    "ThreadStatus",
    "ResearchLedger",
    "ResearchModelUnpriced",
    "ResearchPricing",
    "ResearchQuestion",
    "Reservation",
    "RetentionPolicy",
    "ExpiryReason",
    "ContentTombstone",
    "ContentProvenance",
    "ContentOrigin",
    "Approval", "ApprovalProposal", "ApprovalLifecycle", "ApprovalScope", "BackgroundEvent", "CapabilityCall", "CapabilityAttempt", "CapabilityAttemptDisposition",
    "CapabilityResult", "CapabilityResultState", "ConversationOrigin",
    "ConversationTurn", "Evidence", "GoalMutationKind", "GoalProposal", "GoalState", "GoalStatus", "GoalStopReason",
    "Objective", "ProgressRecord", "Referent", "SuccessCriterion", "WorkItem",
    "CapabilityDefinition", "SideEffect", "StructuredSchema", "ValueKind",
    "StructuredData",
    "SpecialistError", "SpecialistModel", "SpecialistQuestion",
    "AgentDecision", "CapabilityDispatch", "ConversationSnapshot", "DecisionValidationError", "DurableConversationStore", "DurableGoalStore", "DurableMemoryStore", "GoalSnapshot", "GoalSummary", "PendingMemoryBatch", "ReasoningContext", "ReasoningProvider",
    "AudioChunk", "SpeechSynthesizer", "SpeechTranscriber", "TranscriptionEvent",
    "TranscriptionState",
    "ModelCompletion", "ModelMessage", "ModelRequest", "ModelRole",
    "ReasoningModel",
    "MemoryCorrection", "MemoryKind", "MemoryProposal", "MemoryQuery",
    "MemoryRevision", "MemorySnapshot", "MemorySourceMatch",
    "MailAccessError", "MailAccount", "MailAttachment", "MailContent",
    "MailObservationControl", "MailParticipants", "MailReference",
    "MailSearchCriteria", "MailSearchResult",
    "MailSendError", "MailThreading", "OutboundReply", "ReplyOutcome",
    "xero_date",
    "XeroAccessError", "XeroAccountingAccount",
    "DhlDocumentError", "DhlImportAnalyzer",
]
