"""Primitive capability definitions and executor factories."""

from alx.tools.mail import (
    ACKNOWLEDGE_MAIL_MESSAGE,
    DEFINITIONS,
    LIST_MAIL_ATTACHMENTS,
    MARK_MAIL_MESSAGE_SEEN,
    FILE_PROCESSED_MAIL_MESSAGE,
    MOVE_MAIL_MESSAGE_TO_TRASH,
    SEND_DEFINITIONS,
    SEND_MAIL_REPLY,
    READ_MAIL_MESSAGE,
    READ_MAIL_ATTACHMENT,
    SEARCH_MAIL_MESSAGES,
    build_mail_executors,
    build_send_executors,
)
from alx.tools.xero import (
    DELETE_XERO_DRAFT_BILL,
    CAPTURE_SUPPLIER_INVOICE,
    DEFINITIONS as XERO_DEFINITIONS,
    FIND_XERO_BILL,
    LIST_XERO_ACCOUNTS,
    LIST_XERO_TAX_RATES,
    READ_XERO_BILL,
    SEARCH_XERO_CONTACTS,
    build_xero_executors,
)
from alx.tools.notebook import (
    CORRECT_RESEARCH_ENTRY,
    DEFINITIONS as NOTEBOOK_DEFINITIONS,
    DELETE_RESEARCH,
    OPEN_RESEARCH_THREAD,
    READ_RESEARCH_THREAD,
    RECORD_RESEARCH_ENTRY,
    REVISE_RESEARCH_ENTRY,
    SEARCH_RESEARCH,
    SET_RESEARCH_STATUS,
    build_notebook_executors,
)
from alx.tools.research import (
    ASK_RESEARCH_QUESTION,
    DEFINITION as RESEARCH_DEFINITION,
    build_research_executors,
)
from alx.tools.dhl import (
    PROCESS_DHL_IMPORT,
    DEFINITIONS as DHL_DEFINITIONS,
    build_dhl_executors,
)

__all__ = [
    "ACKNOWLEDGE_MAIL_MESSAGE",
    "ASK_RESEARCH_QUESTION",
    "RESEARCH_DEFINITION",
    "build_research_executors",
    "CORRECT_RESEARCH_ENTRY",
    "DELETE_RESEARCH",
    "NOTEBOOK_DEFINITIONS",
    "OPEN_RESEARCH_THREAD",
    "READ_RESEARCH_THREAD",
    "RECORD_RESEARCH_ENTRY",
    "REVISE_RESEARCH_ENTRY",
    "SEARCH_RESEARCH",
    "SET_RESEARCH_STATUS",
    "build_notebook_executors",
    "DEFINITIONS",
    "LIST_MAIL_ATTACHMENTS",
    "MARK_MAIL_MESSAGE_SEEN",
    "FILE_PROCESSED_MAIL_MESSAGE",
    "MOVE_MAIL_MESSAGE_TO_TRASH",
    "SEND_DEFINITIONS",
    "SEND_MAIL_REPLY",
    "READ_MAIL_MESSAGE",
    "READ_MAIL_ATTACHMENT",
    "SEARCH_MAIL_MESSAGES",
    "build_mail_executors",
    "build_send_executors",
    "DELETE_XERO_DRAFT_BILL",
    "CAPTURE_SUPPLIER_INVOICE",
    "PROCESS_DHL_IMPORT",
    "XERO_DEFINITIONS",
    "FIND_XERO_BILL",
    "LIST_XERO_ACCOUNTS",
    "LIST_XERO_TAX_RATES",
    "READ_XERO_BILL",
    "SEARCH_XERO_CONTACTS",
    "build_xero_executors",
    "DHL_DEFINITIONS",
    "build_dhl_executors",
]
